### ISSUE TITLE
There was a problem retrieving table information for the source table. Specified table does not exist: updated_rows. (errorCode=410012)

### ISSUE THREAD

**Issue by JMXAAS** [tableau/hyper-api-samples#103]
using the clouddb-extractor for bigquery, everything works fine except for export_load 

`2023-12-04 13:59:46,171 - TSC wait_for_job - INFO - Job e0f073a1-0e0d-48d4-a1ba-a90266d1250f Completed: Finish Code: 1 - Notes:['com.tableausoftware.server.status.reporting.TableauRuntimeException: There was a problem retrieving table information for the source table. Specified table does not exist: updated_rows. (errorCode=410012)']
Traceback (most recent call last):
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/extractor_cli.py", line 354, in <module>
    main()
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/extractor_cli.py", line 296, in main
    extractor.export_load(
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 182, in execution_timer
    result = func(*args, **kw)
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 778, in export_load
    self.update_datasource_from_hyper_file(
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 668, in update_datasource_from_hyper_file
    self.tableau_server.jobs.wait_for_job(async_job)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/jobs_endpoint.py", line 72, in wait_for_job
    raise JobFailedException(job)
tableauserverclient.server.endpoint.exceptions.JobFailedException: Job e0f073a1-0e0d-48d4-a1ba-a90266d1250f failed with notes ['com.tableausoftware.server.status.reporting.TableauRuntimeException: There was a problem retrieving table information for the source table. Specified table does not exist: updated_rows. (errorCode=410012)']`

Please help!

**Comment by JMXAAS** [comment]
FYI, for smaller tables it actually works fine, but not when you reach 10M rows...

**Comment by JMXAAS** [comment]
[debug_20231204.txt](https://github.com/tableau/hyper-api-samples/files/13548794/debug_20231204.txt)

Thanks alot Francois! Here's the debug of my latest run.

Bigquery
Tableau Online
10,9M Rows

**Comment by FrancoisZim** [comment]
I've created a branch with the fix for this bug: https://github.com/FrancoisZim/hyper-api-samples/tree/clouddb-extractor-bugfix
Can you let me know if this resolves the issue and I will commit to the main repo.

**Comment by JMXAAS** [comment]
Awesome! It worked @FrancoisZim!

Is there some settings in uploading number of rows that can be tweaked? At the moment it just uploads ~400k rows in every chunks to the extract

**Comment by FrancoisZim** [comment]
Thanks for testing.  There is a constant that you can change to include more chunks in each extract.
Odd that you are only getting 400K rows as I thought the default BigQuery behaviour was 1G per chunk - so should be 5G of CSV per hyper file?

BLOBS_PER_HYPER_FILE: int = 5

**Comment by JMXAAS** [comment]
That's what I read as well, but we get ~6Mb chunks of gzipped CSV? 
Yes, I played around with the BLOBS_PER_HYPER_FILE and you clearly see it loads several chunks to the hyperfile. Although what I noticed when increasing the constant was if the hyperfile exceeded the 64Mb limit it started to split the hyperfile to multipart but failed every time. Running the script as with lower constant ending up in hyperfiles below 64Mb worked fine.
I'll see if i can recreate the issue again when exceeding the 64Mb

**Comment by JMXAAS** [comment]
I'll probably manage to try it out tomorrow again

**Comment by JMXAAS** [comment]
[debug_20231207.log](https://github.com/tableau/hyper-api-samples/files/13598408/debug_20231207.log)

@FrancoisZim attaching debug.log from todays test where I increased BLOBS_PER_HYPER_FILE to create a larger hyperfile.

What's not in the logfile is the error message. No extract is published

`Traceback (most recent call last):
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/extractor_cli.py", line 354, in <module>
    main()
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/extractor_cli.py", line 296, in main
    extractor.export_load(
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 182, in execution_timer
    result = func(*args, **kw)
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 776, in export_load
    self.publish_hyper_file(path_to_database, tab_ds_name, publish_mode)
  File "/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 527, in publish_hyper_file
    datasource = self.tableau_server.datasources.publish(datasource, path_to_database, publish_mode)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 292, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 298, in publish
    server_response = self.post_request(url, xml_request, content_type)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 249, in post_request
    return self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 166, in _make_request
    self._check_status(server_response, url)
  File "/usr/local/lib/python3.10/dist-packages/tableauserverclient/server/endpoint/endpoint.py", line 189, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace, url)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        400011: Bad Request
                There was a problem publishing the file '26261:5027d532c029418681b095ae9b659165-0:0'.`
