### ISSUE TITLE
tableauserverclient.server.endpoint.exceptions.InternalServerError:  Error status code: 500

### ISSUE THREAD

**Issue by ramananravishankar** [tableau/hyper-api-samples#47]
Hi, I'm facing error when I try to publish the hyper file to Tableau Server.

Below is the code:

def publish_hyper_file_to_tableau():
    
    server_config = load_server_config()

    hyper_name = server_config['hyper_name']
    server_address = server_config['server_address']
    project_name = server_config['project_name']
    token_name = server_config['token_name']
    token_value = server_config['token_value']
    username = server_config['username']
    password = server_config['password']

    path_to_database = Path(hyper_name)

    # Sign in to server
    tableau_auth = TSC.PersonalAccessTokenAuth(token_name=token_name, personal_access_token=token_value, site_id="")
    server = TSC.Server(server_address, use_server_version=True)
    credentials = TSC.ConnectionCredentials(name=username, password=password)

    print(f"Signing into tableau at {server_address}")

    with server.auth.sign_in(tableau_auth):

        publish_mode = TSC.Server.PublishMode.Overwrite
        
        # Get project_id from project_name
        all_projects, pagination_item = server.projects.get()
        for project in TSC.Pager(server.projects):
            if project.name == project_name:
                project_id = project.id
    
        # Create the datasource object with the project_id
        datasourceitem = TSC.DatasourceItem(project_id)
        
        print(f"Publishing {hyper_name} to {project_name}...")

        # Publish datasource
        datasource = server.datasources.publish(datasourceitem, path_to_database, publish_mode, credentials)
        print("Datasource published. Datasource ID: {0}".format(datasource.id))

Output:

Server config file loaded.
Signing into tableau at ********************* [server name changed for privacy]
Publishing ACE_Dashboard.hyper to ACE_Dashboard...
Traceback (most recent call last):
  File "/home/ramanan/Documents/ACE_Dashboard/ACE_Dashboard/ACE_Dashboard_CSV_To_HYPER .py", line 207, in <module>
    publish_hyper_file_to_tableau()
  File "/home/ramanan/Documents/ACE_Dashboard/ACE_Dashboard/ACE_Dashboard_CSV_To_HYPER .py", line 199, in publish_hyper_file_to_tableau
    datasource = server.datasources.publish(datasourceitem, path_to_database, publish_mode, credentials)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 177, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 219, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 219, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 275, in publish
    raise err
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 271, in publish
    server_response = self.post_request(url, xml_request, content_type)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 140, in post_request
    parameters=parameters,
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 71, in _make_request
    self._check_status(server_response)
  File "/home/ramanan/miniconda3/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 85, in _check_status
    raise InternalServerError(server_response)
tableauserverclient.server.endpoint.exceptions.InternalServerError: 

Error status code: 500
b'<?xml version=\'1.0\' encoding=\'UTF-8\'?><tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-3.13.xsd"><error code="500000"><summary>Internal Server Error</summary><detail>The server encountered an error and cannot complete your request. Contact your server administrator.</detail></error></tsResponse>'

**Comment by jonas-eckhardt** [comment]
You will find more information in the server log files.

**Comment by jonas-eckhardt** [comment]
Did you find a solution for your problem @ramananravishankar?
