### ISSUE TITLE
errorCode=410012 occurred and 6 million rows of BigQuery data could not be published by export_load method

### ISSUE THREAD

**Issue by herobushi** [tableau/hyper-api-samples#79]
## Problem Description
The following error occurred when executing BigQueryExtractor's export_load.

 Specified table does not exist: updated_rows. (errorCode=410012)']

The source table had about 6 million rows, and it seemed that part of the split process at update_datasource_from_hyper_file was failed. 
Checking the destination tableau online source_data, the 1.9 million rows of data was created and not all.

However, when I set sample_rows=10000000 (10M) for load_sample, it worked fine.(but, it took about an hour for local processing...)

Is there something wrong with the settings in export_load? 
Or would it be better to use load_sample for large table (if there is no performance difference with export_load)

I also tried with BigQuery's Public dataset below, but got the same error.
bigquery-public-data.google_trends.top_rising_terms

*Due to a data type error, the following part of bigquery_extractor.py has been temporarily corrected.

`        type_lookup = {
            "BOOL": SqlType.bool(),
            "BYTES": SqlType.bytes(),
            "DATE": SqlType.date(),
            "DATETIME": SqlType.timestamp(),
            "INT64": SqlType.big_int(),
            "INTEGER": SqlType.text(),
            "NUMERIC": SqlType.numeric(18, 9),
            "FLOAT64": SqlType.double(),
            "FLOAT": SqlType.text(),
            "GEOGRAPHY": SqlType.text(),
            "STRING": SqlType.text(),
            "TIME": SqlType.time(),
            "TIMESTAMP": SqlType.timestamp_tz(),
        }`

version:
 - tableauhyperapi:0.0.14401
 - tableauserverclient:0.23

### main.py
    config = yaml.safe_load(open("config.yml"))
    tableau_env = config.get("tableau_env")
    db_env = config.get("bigquery")    
    extractor = BigQueryExtractor(
                source_database_config=db_env,
                tableau_hostname=tableau_env.get("server_address"),
                tableau_project=tableau_env.get("project"),
                tableau_site_id=tableau_env.get("site_id"),
                tableau_token_name="xxxx",
                tableau_token_secret="xxxx",
            )

    extractor.export_load(
                source_table="bigquery-public-data.google_trends.top_rising_terms",
                tab_ds_name="export_load_test"
            )

### Error 

==================
Traceback (most recent call last):
  File "/Users/yuji.yamamoto/test/load_tableau_hyper_files_2/hyper-api-samples/Community-Supported/clouddb-extractor/main.py", line 26, in <module>
    extractor.export_load(
  File "/Users/yuji.yamamoto/test/load_tableau_hyper_files_2/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 165, in execution_timer
    result = func(*args, **kw)
  File "/Users/yuji.yamamoto/test/load_tableau_hyper_files_2/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 690, in export_load
    self.update_datasource_from_hyper_file(
  File "/Users/yuji.yamamoto/test/load_tableau_hyper_files_2/hyper-api-samples/Community-Supported/clouddb-extractor/base_extractor.py", line 584, in update_datasource_from_hyper_file
    self.tableau_server.jobs.wait_for_job(async_job)
  File "/Users/yuji.yamamoto/.anyenv/envs/pyenv/versions/3.9.6/lib/python3.9/site-packages/tableauserverclient/server/endpoint/jobs_endpoint.py", line 72, in wait_for_job
    raise JobFailedException(job)
tableauserverclient.server.endpoint.exceptions.JobFailedException: Job 23a09876-ec23-4d88-b1fa-1314f23f2aef failed with notes ['com.tableausoftware.domain.server.exception.TableauServerException: There was a problem retrieving table information for the source table. Specified table does not exist: updated_rows. (errorCode=410012)']

**Comment by herobushi** [comment]
I modified export_load as attached and it worked fine, so I am closing this ticket for now.
The cause was not clear to me, but I made the process similar to sample_load.

`

    def export_load(
        self,
        tab_ds_name: str,
        source_table: Optional[str] = None,
        sql_query: Optional[str] = None,
        publish_mode: TSC.Server.PublishMode = TSC.Server.PublishMode.CreateNew,
    ) -> None:
        """
        Bulk export the contents of source_table and load to Tableau Server.

        tab_ds_name (string): Target datasource name
        source_table (string): Source table identifier
        sql_query (string): SQL to pass to the source database
        publish_mode: One of TSC.Server.[Overwrite|CreateNew] (default=CreateNew)

        NOTES:
        - Specify either sql_query OR source_table, error if both specified
        """
        sql_query = "SELECT * FROM {}".format(self.quoted_sql_identifier(source_table))
        first_chunk = True
        for path_to_database in self.query_to_hyper_files(sql_query=sql_query):
            if first_chunk:
                self.publish_hyper_file(path_to_database, tab_ds_name, publish_mode)
                first_chunk = False
            else:
                self.update_datasource_from_hyper_file(
                    path_to_database=path_to_database,
                    tab_ds_name=tab_ds_name,
                    action="INSERT",
                )
            os.remove(path_to_database)

`
